'use client';
import { useEffect, useState } from 'react';
import Shell from '../components/normal/Shell';
import PetsBanner from '../components/normal/PetsBanner';
import { categories, categoryFor } from '../lib/normal/categories';
import '../components/normal/pets-banner.css';
export default function Home(){
  const [promo,setPromo]=useState(null);const [settings,setSettings]=useState(null);const [example,setExample]=useState(null);
  useEffect(()=>{fetch('/api/marketing/campaign').then(r=>r.json()).then(d=>{if(d.ok)setPromo(d.campaign)}).catch(()=>{});fetch('/api/settings').then(r=>r.json()).then(d=>{if(d.ok)setSettings(d.settings)}).catch(()=>{});fetch('/api/home/example').then(r=>r.json()).then(d=>{if(d.ok)setExample(d.example)}).catch(()=>{});},[]);
  const cta=settings?.homeV2Button||'Criar página';
  return <Shell>{promo?.showTopBanner&&promo.bannerText?<div className="normal-card" style={{padding:12,textAlign:'center',marginBottom:18}}>{promo.bannerText} {promo.bannerButtonText&&<a href={promo.bannerButtonLink||promo.buttonLink||'/criar'}>{promo.bannerButtonText} →</a>}</div>:settings?.promoBannerEnabled&&settings.promoBannerText?<div className="normal-card" style={{padding:12,textAlign:'center',marginBottom:18}}>{settings.promoBannerText}</div>:null}
    <section className="normal-hero"><div className="normal-hero-copy"><span className="normal-kicker">{settings?.homeV2Badge||'Momentos que sempre ficam'}</span><h1 className="normal-heading">{settings?.homeV2Title||'Celebre momentos que merecem ficar para sempre.'}</h1><p className="normal-subtitle">{settings?.homeV2Subtitle||'Crie páginas emocionantes para pessoas, histórias e momentos especiais da sua vida.'}</p></div><div className="normal-hero-visual"><picture>{!promo?.heroImageUrl&&<source media="(max-width: 600px)" srcSet="/normal/home-portrait.webp"/>}<img src={promo?.heroImageUrl||'/normal/home-wide.webp'} alt="Família e cachorro contemplando o pôr do sol"/></picture><span>Grandes momentos também vivem para sempre.</span></div><div className="normal-hero-action"><a href="/criar" className="normal-button">{cta} <span aria-hidden="true">→</span></a><p className="normal-hint">Comece sem cadastro. Escolha o plano e pague só no final.</p></div></section>
    {settings?.homeV2ShowCategories!==false&&<>
    <div className="normal-quick-categories" aria-label="Momentos para celebrar">{categories.map(cat=><a href="/criar" key={cat.id}><span>{cat.icon}</span><small>{cat.label}</small></a>)}</div>
    <section className="normal-section"><span className="normal-kicker">Para cada fase da vida</span><h2>O que você quer celebrar?</h2><div className="normal-grid">{categories.map(cat=><a className="normal-category" key={cat.id} href="/criar"><img src={cat.image} alt=""/><div><strong>{cat.icon} {cat.label}</strong><small>{cat.subtitle}</small></div></a>)}</div></section>
    </>}
    {settings?.homeV2ShowSteps!==false&&<section className="normal-section"><span className="normal-kicker">Feito para todos</span><h2>Uma história linda, em poucos passos.</h2><div className="normal-steps"><div className="normal-card normal-step-card"><div className="normal-step-picture normal-step-choices" aria-hidden="true">{categories.slice(0,4).map(cat=><div key={cat.id}><img src={cat.image} alt=""/><span>{cat.label}</span></div>)}</div><b>01</b><h3>Escolha o momento</h3><p>Selecione uma categoria e conte essa história com suas palavras.</p></div><div className="normal-card normal-step-card"><div className="normal-step-picture normal-step-memory" aria-hidden="true"><img src="/normal/cards/familia.webp" alt=""/><div><span>Conte essa história do seu jeito</span><i>Um dia para guardar para sempre...</i><small>♡ Fotos · Data · Música</small></div></div><b>02</b><h3>Coloque as memórias</h3><p>Adicione fotos, uma data importante e a música que combina com vocês.</p></div><div className="normal-card normal-step-card"><div className="normal-step-picture normal-step-share" aria-hidden="true"><img src="/normal/cards/namoro.webp" alt=""/><div><span>Nossa história ♡</span><small>Uma página para recordar</small></div><strong>↗ Compartilhar página</strong></div><b>03</b><h3>Compartilhe para sempre</h3><p>Veja a prévia, escolha o plano e pague. Depois, envie o link ou imprima o QR.</p></div></div></section>}
    {example&&<section className="normal-section normal-example"><div className="normal-example-copy"><span className="normal-kicker">Uma página real</span><h2>Uma história para conhecer</h2><span className="normal-pill">{categoryFor(example.category).label}</span><h3>{example.title}</h3>{example.excerpt&&<p>{example.excerpt}</p>}<a href={`/p/${encodeURIComponent(example.slug)}`} className="normal-button">Ver esta página ↗</a></div><a href={`/p/${encodeURIComponent(example.slug)}`} className="normal-example-image" aria-label={`Abrir ${example.title}`}><img src={example.photo||categoryFor(example.category).image} alt="Capa da página de exemplo"/></a></section>}
    <PetsBanner/>
    <section className="normal-section normal-center"><h2>Qual história você quer guardar?</h2><a href="/criar" className="normal-button">{cta} →</a></section>
  </Shell>;
}
