export const PLANS={essencial:{slug:"essencial",name:"Essencial",price:19.9,priceCents:1990},premium:{slug:"premium",name:"Premium",price:39.9,priceCents:3990},eterno:{slug:"eterno",name:"Eterno",price:69.9,priceCents:6990}};
export function getPlanBySlug(slug){return PLANS[slug]||PLANS.premium;}
export function getAsaasBaseUrl(){const env=String(process.env.ASAAS_ENV||"production").toLowerCase();return env==="sandbox"||env==="test"?"https://api-sandbox.asaas.com/v3":"https://api.asaas.com/v3";}
export function getAsaasApiKey(){const apiKey=process.env.ASAAS_API_KEY;if(!apiKey)throw new Error("ASAAS_API_KEY não configurada no ambiente.");return apiKey;}
async function asaasFetch(path,options={}){const response=await fetch(`${getAsaasBaseUrl()}${path}`,{...options,headers:{accept:"application/json",access_token:getAsaasApiKey(),...(options.body?{"content-type":"application/json"}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const message=data?.errors?.[0]?.description||data?.message||data?.error||"Erro ao comunicar com o Asaas.";throw new Error(message);}return data;}
function todayIsoDate(){return new Date().toISOString().slice(0,10);}
export async function createAsaasCustomer({name,email,cpfCnpj}){return asaasFetch("/customers",{method:"POST",body:JSON.stringify({name:name||email||"Cliente Eterniza",email:email||undefined,cpfCnpj:cpfCnpj||(String(process.env.ASAAS_ENV).toLowerCase()==="sandbox"?"12345678909":undefined)})});}
export async function createAsaasPixPayment({tributeId,payerEmail,payerName,plan}){const customer=await createAsaasCustomer({name:payerName||"Cliente Eterniza",email:payerEmail,cpfCnpj:"12345678909"});const payment=await asaasFetch("/payments",{method:"POST",body:JSON.stringify({customer:customer.id,billingType:"PIX",value:Number(plan.price),dueDate:todayIsoDate(),description:`Eterniza - Plano ${plan.name}`,externalReference:tributeId})});const qrCode=await asaasFetch(`/payments/${payment.id}/pixQrCode`,{method:"GET"});return{payment,customer,qrCode};}
export async function getAsaasPayment(paymentId){return asaasFetch(`/payments/${paymentId}`,{method:"GET"});}
