'use client';
import { useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Shell from './Shell';
const destination = (value,fallback) => typeof value==='string' && value.startsWith('/') && !value.startsWith('//') && !value.startsWith('/\\') ? value : fallback;
export default function AuthPage({ register = false }){
  const search=useSearchParams();const [name,setName]=useState('');const [email,setEmail]=useState('');const [phone,setPhone]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  async function submit(e){e.preventDefault();setError('');if(register&&password!==confirm){setError('As senhas não conferem.');return;}setLoading(true);
    try{const res=await fetch(register?'/api/auth/register':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),email:email.trim().toLowerCase(),whatsapp:phone.replace(/\D/g,''),password})});const result=await res.json();if(!res.ok||!result.ok)throw new Error(result.message||'Não foi possível continuar.');
      const fallback=register?'/criar/tipo':result.user.role==='admin'?'/admin':'/minhas-paginas';window.location.assign(destination(search.get('redirect'),fallback));
    }catch(err){setError(err.message);setLoading(false);}
  }
  const query=search.get('redirect')?`?redirect=${encodeURIComponent(search.get('redirect'))}`:'';
  return <Shell compact minimal><div className="normal-auth"><img className="normal-auth-logo" src="/normal/logo-claro.png" alt="Eterniza — Onde Cada História Vive Para Sempre"/><span className="normal-kicker" style={{display:"block",textAlign:"center"}}>Momentos que sempre ficam</span><h1>{register?'Crie sua conta':'Acesse sua conta'}</h1><p className="normal-subtitle">{register?'Sua primeira história está a poucos passos.':'Continue sua página de onde parou.'}</p><form className="normal-card" onSubmit={submit}>{register&&<><label className="normal-field">Seu nome<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></label><label className="normal-field">WhatsApp com DDD<input value={phone} onChange={e=>setPhone(e.target.value)} type="tel" inputMode="tel" autoComplete="tel" required placeholder="(11) 99999-9999"/></label></>}<label className="normal-field">E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required placeholder="seuemail@exemplo.com"/></label><label className="normal-field">Senha<input type={show?'text':'password'} minLength={register?6:undefined} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={register?'new-password':'current-password'} required placeholder={register?'Pelo menos 6 caracteres':'Sua senha'}/></label><label style={{display:'flex',gap:8,alignItems:'center',marginTop:-10,marginBottom:15,fontSize:14}}><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Mostrar senha</label>{register&&<label className="normal-field">Confirme a senha<input type={show?'text':'password'} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required/></label>}{error&&<p role="alert" className="normal-alert">{error}</p>}<button disabled={loading} className="normal-button">{loading?'Aguarde…':register?'Criar conta':'Entrar'}</button></form><p className="normal-auth-bottom">{register?'Já tem conta?':'Ainda não tem conta?'} <a href={`${register?'/login':'/cadastro'}${query}`}>{register?'Entrar':'Criar conta'}</a></p></div></Shell>;
}
