'use client';
import { useEffect,useState } from 'react';
import Shell from './Shell';
import { categoryFor } from '../../lib/normal/categories';
export default function MyPages({account=false}){const [user,setUser]=useState(null),[pages,setPages]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{Promise.all([fetch('/api/auth/me').then(r=>r.json()),fetch('/api/tributes/list').then(r=>r.json())]).then(([auth,list])=>{if(auth.ok)setUser(auth.user);if(list.ok)setPages(list.tributes.filter(page=>!account||page.content?.builderVersion==='2.0'));else setError(list.message);}).catch(()=>setError('Não foi possível carregar suas páginas.')).finally(()=>setLoading(false));},[account]);
  function resume(page){localStorage.setItem(`eterniza:normal:draft:${user.id}`,page.id);window.location.assign(`/criar/tipo?id=${encodeURIComponent(page.id)}`);}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/');}
  return <Shell><span className="normal-kicker">Sua conta Eterniza</span><h1 className="normal-heading">{account?'Minha conta':'Minhas páginas'}</h1>{user&&<p className="normal-subtitle">Olá, {user.name?.split(' ')[0]}! {account?'Seu espaço para acompanhar suas histórias.':'Retome seus rascunhos ou compartilhe suas páginas publicadas.'}</p>}{account&&user&&<div className="normal-card"><h2>Dados da conta</h2><p><strong>Nome:</strong> {user.name}<br/><strong>E-mail:</strong> {user.email}</p><button type="button" className="normal-button secondary" onClick={logout}>Sair da conta</button></div>}<div style={{margin:'25px 0'}}><a href="/criar" className="normal-button">＋ Criar nova página</a></div>{account&&<h2 style={{fontFamily:'Georgia,serif'}}>Suas páginas recentes</h2>}{loading?<p>Carregando suas páginas…</p>:error?<p role="alert" className="normal-alert">{error}</p>:pages.length===0?<div className="normal-card normal-empty"><h2>Sua primeira história começa aqui ♡</h2><p>Escolha uma categoria e crie uma página especial.</p><a className="normal-button" href="/criar">Criar minha página →</a></div>:<div className="normal-page-list">{pages.map(page=><article key={page.id} className="normal-card normal-page-row"><div><span className="normal-pill">{categoryFor(page.category).label} · {page.status==='PUBLISHED'?'Publicada':'Rascunho'}</span><h2>{page.title||page.receiver_name||'Minha página'}</h2><p>{new Date(page.updated_at).toLocaleDateString('pt-BR')} · {page.photos_count||0} fotos</p></div><div className="normal-actions">{page.status==='PUBLISHED'?<a className="normal-button" href={page.content?.builderVersion==='2.0'?`/p/${page.slug}`:page.public_url}>Ver e compartilhar ↗</a>:page.content?.builderVersion==='2.0'?<><button type="button" className="normal-button secondary" onClick={()=>resume(page)}>Continuar criando</button>{page.plan_id&&<a className="normal-button" href={`/pagamento?id=${encodeURIComponent(page.id)}`}>Concluir pagamento</a>}</>:<a className="normal-button" href="/criar-classico">Abrir editor clássico</a>}</div></article>)}</div>}</Shell>;
}
