'use client';
import { useEffect,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import Shell from './Shell';
const money=n=>(Number(n||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function Plans(){const router=useRouter(),search=useSearchParams(),id=search.get('id');const [plans,setPlans]=useState([]),[draft,setDraft]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState('');
  useEffect(()=>{fetch('/api/plans').then(r=>r.json()).then(d=>{if(d.ok)setPlans(d.plans);else setError(d.message)}).catch(()=>setError('Não foi possível carregar os planos.'));if(id)fetch(`/api/tributes/draft?id=${encodeURIComponent(id)}`).then(r=>r.json()).then(d=>{if(d.ok)setDraft(d.tribute);else setError(d.message)}).catch(()=>{});},[id]);
  async function choose(plan){if(!id){router.push('/criar');return;}setError('');setLoading(plan.slug);try{const response=await fetch('/api/tributes/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tributeId:id,content:{...draft.content,plan:{slug:plan.slug}}})});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.message);router.push(`/pagamento?id=${encodeURIComponent(id)}`);}catch(e){setError(e.message||'Erro ao selecionar o plano.');setLoading('');}}
  return <Shell><span className="normal-kicker">Últimos passos</span><h1 className="normal-heading">Escolha seu plano</h1><p className="normal-subtitle">Sua história será publicada após a confirmação do pagamento. Os valores e limites abaixo vêm dos planos configurados na sua conta.</p>{draft&&<p className="normal-hint">Página: <strong>{draft.title}</strong> · {draft.content?.photos?.length||0} fotos</p>}{error&&<p role="alert" className="normal-alert">{error}</p>}<div className="normal-plan-grid">{plans.map(plan=><article className="normal-card normal-plan" key={plan.slug}><span className="normal-pill">{plan.slug==='premium'?'Mais escolhido':'Eterniza'}</span><strong>{plan.name}</strong><span className="price">{money(plan.priceCents ?? plan.cents)}</span><p>{plan.description || 'Para guardar uma história especial.'}</p><p>✓ Até {plan.photos} fotos<br/>✓ Música do YouTube<br/>✓ Página para compartilhar<br/>✓ {plan.duration||'Confira a duração do plano'}</p><button className="normal-button" type="button" disabled={!!loading||!draft&&!!id} onClick={()=>choose(plan)}>{loading===plan.slug?'Aguarde…':'Escolher '+plan.name} →</button></article>)}</div><p className="normal-hint">O pagamento é processado por PIX via Asaas.</p></Shell>;
}
