-- V55 - Campos necessários para a experiência atual da Eterniza usando Prisma como camada principal.
ALTER TABLE "Tribute" ALTER COLUMN "category" DROP NOT NULL;
ALTER TABLE "Tribute" ALTER COLUMN "music" TYPE JSONB USING CASE WHEN "music" IS NULL THEN NULL ELSE to_jsonb("music") END;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "content" JSONB;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "receiverName" TEXT;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "senderName" TEXT;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "specialDate" TIMESTAMP(3);
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "planId" TEXT;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "planName" TEXT;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "planPriceCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "publicUrl" TEXT;
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
ALTER TABLE "Tribute" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);
